Room.create(name: "Luke")
Room.create(name: "Muke")
Room.create(name: "Duke")
Room.create(name: "Game1")
Room.create(name: "Time")
Room.create(name: "Cloudy")
Room.create(name: "Sun")
Room.create(name: "Moon")
